name: CVE scan 12

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cve_scan:
    name: CVE scan on dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
     
      - name: Get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      - name: Get cached database
        uses: actions/cache@v2
        with:
          path: ~/.cache/cve-bin-tool
          key: ${{ runner.os }}-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install dependencies and cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          pip install cve-bin-tool
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
      - name: Test to check for CVEs for Python requirements and HTML report dependencies
        run: |
            cve-bin-tool -n json -i pom.xml -o report

